services: 
  carselon: 
    container_name: carselon
    restart: always
    image: node:20.18.1
    ports: 
      - 4000:4444
    volumes: 
      - ./:/user/src/carselon
    working_dir: /user/src/carselon

    networks: 
      - monorepo-network
    
    command: bash -c "rm -rf dist && npm install && npm run build && npm run start:prod"


  carselon-batch: 
    container_name: carselon-batch
    restart: unless-stopped
    image: node:20.18.1
    ports: 
      - 2000:2222
    volumes: 
      - ./:/user/src/carselon
    working_dir: /user/src/carselon

    networks: 
      - monorepo-network
    
    command: bash -c "npm install && npm run build && npm run start:prod:batch"


networks: 
  monorepo-network:
    driver: bridge
